const express = require("express");
const route = new express.Router();
const authcontroller = require("../controllers/auth-controller");
route.get("/", authcontroller.home);
route.post("/register", authcontroller.register);
route.post("/login", authcontroller.login);
route.get("/goaldata/:id", authcontroller.goaldata);
route.post("/todo", authcontroller.todo);
route.post("/incomplete", authcontroller.incomplete);
route.post("/complete", authcontroller.complete);
route.post("/deletetask", authcontroller.deletetask);
module.exports = route;
